### ISSUE TITLE
I need install gadl in the window？

### ISSUE THREAD

**Issue by ChineseHero** [wavded/ogr2ogr#44]
H:\html\test\samples\sample.lonely.shp
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Error: spawn ogr2ogr ENOENT
    at ChildProcess.<anonymous> (H:\html\koa\node_modules\ogr2ogr\index.js:222:18)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
Emitted 'error' event at:
    at wrapUp (H:\html\koa\node_modules\ogr2ogr\index.js:237:15)
    at H:\html\koa\node_modules\ogr2ogr\modules\util.js:56:5
    at ChildProcess.<anonymous> (H:\html\koa\node_modules\ogr2ogr\index.js:222:7)
    at ChildProcess.emit (events.js:189:13)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:600:12)
[Finished in 0.8s]

**Comment by ChineseHero** [comment]
Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   gdal

  Path            gdal > node-pre-gyp > needle > debug

  More info       https://nodesecurity.io/advisories/534

found 1 low severity vulnerability in 455 scanned packages
  1 vulnerability requires manual review. See the full report for details.
npm install ogr2ogr --save  problem
